// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_W_Yj8E5Sr0fulkHqZOeR-8s92Rh5YA',
    appId: '1:317898603222:web:d8ae7011ee36690bb9a777',
    messagingSenderId: '317898603222',
    projectId: 'chhaatra-7fb15',
    authDomain: 'chhaatra-7fb15.firebaseapp.com',
    databaseURL: 'https://chhaatra-7fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chhaatra-7fb15.firebasestorage.app',
    measurementId: 'G-8KMXJM0EBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZaf_7N1ma9agC94rPllwp4R8Zk8Qbs4',
    appId: '1:317898603222:android:b0dd77bab065be7cb9a777',
    messagingSenderId: '317898603222',
    projectId: 'chhaatra-7fb15',
    databaseURL: 'https://chhaatra-7fb15-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chhaatra-7fb15.firebasestorage.app',
  );

}